From ubuntu:xenial

RUN apt-get update && apt-get install -y \
    build-essential \
    ca-certificates \
    gcc \
    git \
    python-pip \
    python2.7 \
    python2.7-dev \
    python-tk \
    ssh \
    wget \
    && apt-get autoremove \
    && apt-get clean

RUN pip install -U "setuptools"
RUN pip install -U "pip"
RUN pip install -U "matplotlib"
RUN pip install -U "nibabel"
RUN pip install -U "numpy"
RUN pip install -U "scipy"
RUN pip install -U "scikit-image==0.13.1"
RUN pip install -U "docopt"
RUN pip install -U "pandas"

RUN wget http://fsl.fmrib.ox.ac.uk/fsldownloads/fslinstaller.py \
    && python fslinstaller.py -E -V 5.0.10 -d /usr/local/fsl \
    && rm fslinstaller.py \
    && rm fsl.csh \
    && rm fsl.sh

# Manually set up the FSL environment, since the fsl.sh script generated by
# the fslinstaller.py is broken
ENV PATH /usr/local/fsl/bin:/usr/local/fsl/lib:$PATH
ENV FSLDIR /usr/local/fsl
ENV FSLOUTPUTTYPE NIFTI_GZ
ENV FSLMULTIFILEQUIT TRUE
ENV FSLPARALLEL 1
ENV SGE_ON false

RUN mkdir FeenICS
RUN mkdir ICArus

RUN git clone https://github.com/eziraldo/FeenICS.git /FeenICS/
RUN git clone https://github.com/edickie/ICArus.git /ICArus/

ENV PATH $PATH:/FeenICS/bin:/usr/share/fsl/5.0:/ICArus/bin
ENV PYTHONPATH $PYTHONPATH:/FeenICS/bin:/ICArus/bin

RUN chmod +x /FeenICS/bin/*
RUN chmod +x /ICArus/bin/*

ENTRYPOINT ["/bin/bash"]
